name: mocktail
description: A Dart mock library which simplifies mocking with null safety support and no manual mocks or code generation.
version: 0.3.0
repository: https://github.com/felangel/mocktail
homepage: https://github.com/felangel/mocktail/tree/main/packages/mocktail

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  test: ^1.22.0

dev_dependencies:
  meta: ^1.8.0
